#!/usr/bin/env bash
menu=$(printf '%s\n' \
  'zen' \
  'firefox' \
  'brave --profile-directory=Default' \
  '| wl-copy -n' |
  wofi --show=dmenu -p "Open URL with:")
STR="$*"
case "$menu" in
'zen')
  zen "$STR" >/dev/null 2>&1 &
  ;;
'firefox')
  firefox "$STR" >/dev/null 2>&1 &
  ;;
'brave --profile-directory=Default')
  brave --profile-directory=Default "$STR" >/dev/null 2>&1 &
  ;;
'| wl-copy -n')
  printf '%s' "$STR" | wl-copy -n >/dev/null 2>&1 &
  ;;
esac
